image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_DEV: $CI_REGISTRY/$CI_PROJECT_PATH/microsite:dev-latest

stages:
  - build

before_script:
  - docker login -u "quest-ci" -p "$CI_JOB_TOKEN" registry.green-light.com
  - IMAGE_NAME=dev-$(echo $CI_COMMIT_SHA | cut -c 1-7)
  - DEV_TAG=$CI_REGISTRY/$CI_PROJECT_PATH/microsite:latest-dev
  - PROD_TAG=$CI_REGISTRY/$CI_PROJECT_PATH/microsite:latest-prod

build-dev:
  stage: build
  script:
    - docker pull $IMAGE_DEV || true
    - docker build --build-arg CONFIG_ENV=dev --cache-from $IMAGE_DEV --tag $IMAGE_DEV --tag $CI_REGISTRY/$CI_PROJECT_PATH/microsite:$IMAGE_NAME .
    
  ### GET JWT TOKEN FOR REGISTRY using $GITLAB_ACCESS_TOKEN as login
    - 'curl https://$CI_REGISTRY/jwt/auth
        --get
        --v
        --include
        -d client_id=docker
        -d offline_token=true
        -d service=container_registry
        -d "scope=repository:$IMAGE_DEV:pull,*"
        --fail
        --user "quest-ci:$CI_JOB_TOKEN"'
  ### EXTRACT JWT TOKEN FROM JSON ANSWER 
    - 'export CI_REGISTRY_TOKEN=$(
        curl https://$CI_REGISTRY/jwt/auth
        --get
        -d client_id=docker
        -d offline_token=true
        -d service=container_registry
        -d "scope=repository:$IMAGE_DEV:pull,*"
        --fail
        --user "quest-ci:$CI_JOB_TOKEN"
        | sed -r "s/(\{\"token\":\"|\"\})//g"
      )'
  ### EXTRACT SHA OF TAG TO BE DELETED USING DOCKER REGISTRY API
    - 'export MANIFEST_SHA_TO_BE_DELETED=$(
        curl https://$CI_REGISTRY/v2/$CI_PROJECT_PATH/microsite/manifests/dev-latest
          --head 
          --fail
          -H "accept: application/vnd.docker.distribution.manifest.v2+json"
          -H "authorization: Bearer $CI_REGISTRY_TOKEN"
        | grep -i "Docker-Content-Digest"
        | grep -o -i "sha256:\w\+"
      )'
  ### DELETE TAG
    - 'curl "https://$CI_REGISTRY/v2/$CI_PROJECT_PATH/microsite/manifests/$MANIFEST_SHA_TO_BE_DELETED"
        -X DELETE
        --include
        -v
        -H "accept: application/vnd.docker.distribution.manifest.v2+json"
        -H "authorization: Bearer $CI_REGISTRY_TOKEN"'
    
    - docker push $IMAGE_DEV
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/microsite:$IMAGE_NAME
  tags:
    - docker
    - vshosting-cluster
  only:
    - dev


    