image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_DEV: $CI_REGISTRY/$CI_PROJECT_PATH/microsite:dev-latest

stages:
  - build

before_script:
  - docker login -u "quest-ci" -p "$CI_JOB_TOKEN" registry.green-light.com
  - IMAGE_NAME=dev-$(echo $CI_COMMIT_SHA | cut -c 1-7)
  - DEV_TAG=$CI_REGISTRY/$CI_PROJECT_PATH/microsite:latest-dev
  - PROD_TAG=$CI_REGISTRY/$CI_PROJECT_PATH/microsite:latest-prod

build-dev:
  stage: build
  script:
    - docker pull $IMAGE_DEV || true
    - docker build --build-arg CONFIG_ENV=dev --cache-from $IMAGE_DEV --tag $IMAGE_DEV --tag $CI_REGISTRY/$CI_PROJECT_PATH/microsite:$IMAGE_NAME .
    #- docker build --build-arg CONFIG_ENV=dev --pull -t "$DEV_TAG" .
    #- docker push "$DEV_TAG"
    - docker push $IMAGE_DEV
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/microsite:$IMAGE_NAME
  tags:
    - docker
    - vshosting-cluster
  only:
    - dev